### ISSUE TITLE
8.1.5 Error

### ISSUE THREAD

**Issue by Comicus** [fubaWoW/HandyNotes_WorldMapButton#1]
Mousing over button on World Map causes:

4x ...dyNotes_WorldMapButton\HandyNotes_WorldMapButton-80000.01-Release.lua:47: attempt to index global 'WorldMapTooltip' (a nil value)
...dyNotes_WorldMapButton\HandyNotes_WorldMapButton-80000.01-Release.lua:47: in function <...dyNotes_WorldMapButton\HandyNotes_WorldMapButton.lua:45>

Locals:
self = HandyNotesWorldMapButton {
 0 = <userdata>
 Text = HandyNotesWorldMapButtonText {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}
motion = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WorldMapTooltip' (a nil value)"

**Comment by fubaWoW** [comment]
hmm interesting...
should be fixed now but...
there should **always** be a WorldMapTooltip  
if it is no there is something wrong with the default UI
