### ISSUE TITLE
Toggle button is underneath the magnifying glass icon of the World map

### ISSUE THREAD

**Issue by lotharschaberg** [fubaWoW/HandyNotes_WorldMapButton#4]
Hi,

since today's update the button is shown on the world map itself, but unfortunately the magnifying glass icon of the world map is shown on top of the toggle button. I am using ElvUI and when I disable it, things even get worse - it is nearly impossible to click the toggle World Map button.
![2020-09-10_18h56_50](https://user-images.githubusercontent.com/20385649/92768982-d1e13f80-f398-11ea-8391-3359d038d335.jpg)
![2020-09-10_18h57_35](https://user-images.githubusercontent.com/20385649/92768983-d1e13f80-f398-11ea-99ca-91b978a40042.jpg)

**Comment by reaper666735** [comment]
yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)

**Comment by reaper666735** [comment]
yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)

**Comment by reaper666735** [comment]
yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)

**Comment by reaper666735** [comment]
yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)

**Comment by reaper666735** [comment]
yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)

**Comment by reaper666735** [comment]
yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)

**Comment by fubaWoW** [comment]
> Hi,
> 
> since today's update the button is shown on the world map itself, but unfortunately the magnifying glass icon of the world map is shown on top of the toggle button. I am using ElvUI and when I disable it, things even get worse - it is nearly impossible to click the toggle World Map button.
> ![2020-09-10_18h56_50](https://user-images.githubusercontent.com/20385649/92768982-d1e13f80-f398-11ea-8391-3359d038d335.jpg)
> ![2020-09-10_18h57_35](https://user-images.githubusercontent.com/20385649/92768983-d1e13f80-f398-11ea-99ca-91b978a40042.jpg)

Yeah i see, maybe i'll take a look into it later.
seems you use an addon that conflicts with my button becasue the Original UI no longer have it!


> yeah i'm having the same issue since latest update , but i am using [world map tracking enhanced](https://www.curseforge.com/wow/addons/world-map-tracking-enhanced) with similar magnifying glass position, it used to be better when it was located on the top bar near the minimize/maximize button :)
yeah...
you know world map tracking enhanced also have the function to toggle Handynotes? :D

**Comment by fubaWoW** [comment]
moved the Button to the LEFT side of the map
should be no problem anymore anything overwrites my button.

**Comment by reaper666735** [comment]
yes i know WMTE  has the toggle ability as well :p , but one click is faster then having to open several tabs ;)

**Comment by fubaWoW** [comment]
should work now in update 80300.04.. hopefully ^^
