### ISSUE TITLE
Lua Error on BCC when opening map.

### ISSUE THREAD

**Issue by b-morgan** [fubaWoW/HandyNotes_WorldMapButton#6]
This error occurs both with and without the addon Mapster.

2x ...dyNotes_WorldMapButton\HandyNotes_WorldMapButton-20501.01-BBC.lua:95: attempt to index local 'alignmentFrame' (a nil value)
[string "@HandyNotes_WorldMapButton\HandyNotes_WorldMapButton-20501.01-BBC.lua"]:95: in function <...dyNotes_WorldMapButton\HandyNotes_WorldMapButton.lua:86>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Accountant_Classic\Libs\AceHook-3.0\AceHook-3.0-9.lua"]:95: in function <...\Accountant_Classic\Libs\AceHook-3.0\AceHook-3.0.lua:87>
[string "=[C]"]: in function `Show'
[string "@Mapster\Mapster-1.9.3.lua"]:110: in function <Mapster\Mapster.lua:110>
[string "=(tail call)"]: ?
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:182: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
self = WorldMapFrame {
 isUndefinedEventAllowed = true
 ShouldPanOnClick = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:624
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:491
 PanTo = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:591
 AreDetailLayersLoaded = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:405
 RemovePin = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:184
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:535
 CalculatePinNudging = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:303
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:551
 HandleUserActionToggleSelf = <function> defined @Accountant_Classic\Libs\AceHook-3.0\AceHook-3.0.lua:100
 SetAreaTriggerIntersectsCallback = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:249
 ShouldZoomInstantly = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:632
 expandedMapInsetsByMapID = <table> {
 }
 pinNudgingDirty = true
 SetGlobalPinScale = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:773
 RefreshDebugAreaTriggers = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:358
 SetShouldNavigateOnClick = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:612
 NavigateToParentMap = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:722
 SetDebugAreaTriggersEnabled = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:382
 UnregisterEvents = <function> defined @SharedXML\CallbackRegistry.lua:142
 EvaluateLockReasons = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:694
 GetGlobalPinScale = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:769
 OnLoad = <function> defined @Blizzard_WorldMap\Blizzard_WorldMap.lua:13
 RemoveDataProviderEvent = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:97
 GetNumActivePinsByTemplate = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:200
 SetPinTemplateType = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:173
 SetAreaTriggerEnclosedCallback = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:244
 IsCanvasMouseFocus = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:680
 GetCanvasScale = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:555
 SetGlobalAlpha = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:786
 RemoveDataProvider = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:86
 lockReasons = <table> {
 }
 GetScaleForMinZoom = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:652
 NavigateToCursor = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:729
 AdjustDetailLayerAlpha = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:414
 callbackTables = <table> {
 }
 SetShouldZoomInstantly = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:628
 IsAtMinZoom = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:587
 UpdatePinNudging = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:331
 ProcessCanvasClickHandlers = <function> defined @Blizzard_MapCanvas\Blizzard_MapCanvas.lua:759
 pinPools = <table> {
 }
 dataProviderEventsCount = <table> {
 }
 HasRegistrantsForEvent = <function> defined @SharedXML\CallbackRegistry.lua:63
 mouseClickHandlers = <table> {
 }
 SetShouldZoomInOnClick = <fun

**Comment by b-morgan** [comment]
I believe the issue is on line 5 of HandyNotes_WorldMapButton.lua:

`local isClassicWow = select(4,GetBuildInfo()) < 20000`

The following change will allow it to work on both Classic and Burning Crusade Classic:

`local isClassicWow = WOW_PROJECT_ID == WOW_PROJECT_CLASSIC or WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC`

**Comment by fubaWoW** [comment]
should be fixed in new versions, but i have no active subscription and i can not test it right now.
maybe you can test it and report?
thanks :)
